import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar";
import { EventProvider } from "./context/eventContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-background text-black">
        <EventProvider>
          <NavBar />
          {children}
        </EventProvider>
      </body>
    </html>
  );
}
